### ISSUE TITLE
[STAR-1] Initial project structure

### ISSUE THREAD

**Issue by filiphsps** [NordcomInc/nordstar#23]
* [X] `TurboRepo` configuration.
* [X] `<NordstarProvider/>`.
* [X] Stub sites.
  * [X] Docs ([https://nordstar.nordcom.io/docs/](https://nordstar.nordcom.io/docs/)).
  * [X] Showcase (root of [https://nordstar.nordcom.io/](https://nordstar.nordcom.io/)).
* [X] CI quality assurance.
  * [X] Unit testing (`vitest`).
  * [X] Linting (`eslint`).
  * [X] Style checking (`prettier`).
  * [X] Type checking (`tsc`).
* [X] Release management .
  * [X] Automatic version bumping.
  * [X] Automatic tagging.
  * [X] Packages.
    * [X] Automatically publish on `npm`.
  * [X] Automatic GitHub releases and pre-releases.
* [ ] Project management.
  * [X] Sync Linear with GitHub issues.
  * [X] Project documentation.
    * [X] `README.md`.
    * [X] `LICENSE`.
    * [X] `SECURITY.md`.
    * [X] `CONTRIBUTING.md` https://github.com/NordcomInc/nordstar/pull/35.
  * [ ] [PR template.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

And anything else I've forgotten about.

<sub>From [SyncLinear.com](https://synclinear.com) | [STAR-1](https://linear.app/nordcom/issue/STAR-1/initial-project-structure)</sub>
